#!/bin/bash
#
# goenv.run: Simple launcher for goenv-installer
# Usage: curl -fsSL https://alexcaraballo.github.io/goenv.run | bash
#

index_main() {
    set -e
    curl -s -S -L https://raw.githubusercontent.com/alexcaraballo/goenv-installer/main/bin/goenv-installer | bash
}

index_main